App/views/routes.py
from flask import Blueprint, request, render_template, flash, redirect, url_for, jsonify, session
from flask_login import login_required, logout_user, login_user, current_user
from flask_admin.base import BaseView, expose, AdminIndexView, Admin
from flask_socketio import emit, join_room, leave_room, send, rooms
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime

from App.models import User, Cerita, Chat, SuperSU
from App import db, admin, login_manager, socketio

views = Blueprint('views', __name__)

@views.route('/', methods=['POST', 'GET'])
def index():
    if current_user.is_authenticated:
        if current_user.account_type == 'admin':
            return redirect(url_for('views.dashboard'))
        elif current_user.account_type == 'user':
            return redirect(url_for('views.home'))

    if request.method == 'POST':
        email = request.form['emailAddress']
        password = request.form['userPassword']
        
        user = User.query.filter_by(email=email).first()

        if user and check_password_hash(user.password, password):
            session['account_type'] = 'user'
            flash("Berhasil Masuk!", category='success')
            login_user(user, remember=True)
            return redirect(url_for('views.home'))
        elif user is None:
            flash(f"Akun dengan email {email} tidak ditemukan. Silakan daftar terlebih dahulu!",'warning')
            return redirect(url_for('auth.login'))
        else:
            flash("Kata sandi salah, coba lagi.", 'error')
            return redirect(url_for('auth.login'))
    return render_template('index.html')

@views.route('/beranda', methods=['GET', 'POST'])
@login_required
def home():
    if current_user.is_authenticated and session['account_type'] == 'user':
        postingan = Cerita.query.all()
        user = User.query.all()

        if request.method == 'POST':
            teks = request.form['tulisan']
            anonym = True if request.form.get('anonim') == 'on' else False

            cerita = Cerita(konten=teks, tanggal=datetime.utcnow(), status=False, anonym=anonym, user_id=current_user.id)
            db.session.add(cerita)
            db.session.commit()
            print('Cerita berhasil dibuat!')
            return redirect(request.referrer)
        return render_template('beranda.html', postingan=postingan, user=user)
    elif current_user.is_authenticated and session['account_type'] == 'admin':
        return redirect(url_for('views.dashboard'))
    else:
        return redirect(url_for('auth.login'))
    
@views.route('/profil/<string:username>', methods=['GET', 'POST'])
@login_required
def profil(username):
    if current_user.is_authenticated and session['account_type'] == 'user':
        # user = User.query.filter_by(username=username)
        user = User.query.filter_by(username=username).first()

        if request.method == 'POST':
            if user:
                password = request.form['password']
                if check_password_hash(user.password, password):
                    # update_user = User(nama_lengkap=full_name, email=email,
                    #                   username=username, password=generate_password_hash(password, method='pbkdf2'),
                    #                   room_id=user.room_id, cerita=user.cerita, chat=user.chat)

                    # db.session.delete(user)
                    # db.session.add(update_user)
                    user.nama_lengkap = request.form['nama_lengkap']
                    user.username = request.form['username']
                    user.email = request.form['email']
                    user.password = generate_password_hash(request.form['password'], method='pbkdf2')
                    db.session.commit()
                    flash('Akun berhasil diubah!', category='success')
                    print('Akun berhasil diperbarui!')
                    return redirect(url_for('views.profil', username=username))
                else:
                    flash("Kata sandi salah, silakan coba lagi.", category='danger')
                    return redirect(url_for('views.profil', username=user.username))

        post = Cerita.query.filter_by(user_id=current_user.id).all()
        return render_template("profil.html", user=user, post=post)

        # ... other code for admin and unauthorized access


    elif current_user.is_authenticated and session['account_type'] == 'admin':
        return render_template("admin_profile.html")
    else:
        return redirect(url_for('auth.login'))

@views.route('/about')
def about():
    return render_template('about.html')


# +++++++++++++++++++++++++++++++++++++ CHAT ROOM SESSION ++++++++++++++++++++++++++++++++++++++++

# page = request.args.get('page', 1, type=int)
# per_page = 10  # Ubah sesuai kebutuhan
# messages = Chat.query.filter_by(room_id=room).order_by(Chat.timestamp.desc()).paginate(page, per_page, error_out=False)
# chatContent = messages.items

@views.route('/chat/<string:room>/', defaults={'page_num': 1})
@views.route('/chat/<string:room>/<int:page_num>')
@login_required
def chat(room, page_num):
    user = User.query.all()
    superuser = SuperSU.query.filter_by(account_type='admin').first()
    if user or superuser:
        msgs = Chat.query.filter_by(room_id=room).order_by(Chat.tanggal.desc()).paginate(page=page_num, per_page=5)
        return render_template('chat_room.html', room=room, user=user, msgs=msgs, error_out=True)
    else:
        return "User not found", 404

# @views.route('/get_messages', methods=['GET'])
# def get_messages():
#     page = request.args.get('page', 1, type=int)
#     per_page = 10  # Ubah sesuai kebutuhan

#     messages = Chat.query.order_by(Chat.timestamp.desc()).paginate(page, per_page, error_out=False)
#     messages_data = [{'content': msg.content, 'user_id': msg.user_id} for msg in messages.items]

#     return jsonify({'messages': messages_data, 'has_next': messages.has_next})

@views.route('/chat/delete_chat/<string:room>', methods=['GET'])
def delete_chat(room):
    # Use the SQLAlchemy delete() method to delete all rows
    chat = Chat.query.filter_by(room_id=room).all()
    for chats in chat:
        db.session.delete(chats)
    
    # Commit the changes to the database
    db.session.commit()

    return redirect(request.referrer)

@socketio.on("connect")
def connect():
    print("Client connected!")

@socketio.on('online')
def online(data):
    emit('status_change', {'username': data['username'], 'status': 'online'}, broadcast=True)

@socketio.on("user_join")
def user_join(room):
    username = current_user.username
    join_room(room)
    if session['account_type'] == 'admin':
        chats = Chat.query.filter_by(room_id=room).all()
        for chat in chats:
            chat.read = True
        db.session.commit()
    emit('join', {'username':username}, to=room)
    print(f"Client {username} joined to {room}!")

@socketio.on("new_message")
def handle_message(message, room):
    username = current_user.username
    if room in rooms():
        emit('chat', {'username':username, 'message':message}, broadcast=True, to=room)

    print(f"New message: {message} from {username}")
    msg_content = Chat(pesan=message, tanggal=datetime.utcnow(), sender=current_user.username, room_id=room, user_id=current_user.id)
    db.session.add(msg_content)
    db.session.commit()

@socketio.on('leave')
def leave(room):
    username = current_user.username
    room = room
    print(f"{username} leave room")
    leave_room(room)
    emit('leave', {'username': username}, to=room)

# +++++++++++++++++++++++++++++++ CHAT ROOM SESSION ++++++++++++++++++++++++++=


# todo =========================== ADMIN SECTION =================================
@views.route('/adminProfile/<string:username>', methods=['GET', 'POST'])
@login_required
def adminProfile(username):
    if current_user.is_authenticated and current_user.account_type == 'admin':
        user = SuperSU.query.filter_by(username=username).first()

        if request.method == 'POST':
            if user:
                db.session.delete(user)
                db.session.commit()
                username = request.form['username']
                password = request.form['password']

                if check_password_hash(user.password, password):
                    update_user = SuperSU(username=username, password=generate_password_hash(password, method='pbkdf2'))
                    db.session.add(update_user)
                    db.session.commit()
                    flash('Akun berhasil diubah!', category='success')
                    print('Akun berhasil diperbarui!')
                    return redirect(url_for('views.adminProfile', username=username))
        return render_template("admin_profile.html")
    
    elif current_user.is_authenticated and current_user.account_type == 'user':
        return render_template("profil.html")
    else:
        return redirect(url_for('auth.adminlogin'))

@views.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    if current_user.is_authenticated and current_user.account_type == 'admin':
        user_data = User.query.all()
        cerita = Cerita.query.all()
        chat = Chat.query.filter_by(read=False).all()
        chat_counts = {user.room_id: sum(1 for chats in chat if chats.room_id == user.room_id and chats.read == False) for user in user_data}
        return render_template('dashboard.html', user_data=user_data, cerita=cerita, chat=chat, chat_counts=chat_counts)
    elif current_user.is_authenticated and current_user.account_type == 'user':
        return redirect(url_for('views.home'))
        
    else:
        return redirect(url_for('auth.login'))


@views.route('/dashboard/approve_post/<int:id>', methods=['GET'])
def approve_post(id):
    post = Cerita.query.get_or_404(id)
    post.status = True
    db.session.commit()
    return redirect(url_for('views.dashboard'))

App/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- FAVICONS -->
        <link rel="icon" type="image/svg+xml" href="{{ url_for('static', filename='src/favicons/favicon.svg' ) }}" />
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='src/favicons/favicon.png' ) }}" />
        <title>{% block title %} {% endblock %}</title>

        <!-- FONTS -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Plus+Jakarta+Sans" />

        <!-- CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css' ) }}" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />

        <!-- JS -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"
        ></script>
        <script src="https://cdn.socket.io/4.7.4/socket.io.min.js" integrity="sha384-Gr6Lu2Ajx28mzwyVR8CFkULdCU7kMlZ9UthllibdOSo6qAiN+yXNHqtgdTvFXMT4" crossorigin="anonymous"></script>
    </head>
    <body>
        {% block body %} {% endblock %}
    </body>
</html>

App/templates/beranda.html
{% extends 'base.html' %} {% block title %} Beranda {% endblock %} {% block body %}

<body>
    <img src="{{ url_for('static', filename='src/img/SR element.png') }}"
        class="position-absolute bottom-0 end-0 d-none d-lg-block" alt="" />
    <img src="{{ url_for('static', filename='src/img/SR element 2.png') }}"
        class="position-absolute bottom-0 start-0 d-none d-lg-block" alt="" />
    <header>
        <nav class="navbar navbar-expand-lg bg-white">
            <div class="container">
                <a class="navbar-brand" href="/"><img
                        src="{{ url_for('static', filename='src/img/SARITA LOGO 2.png') }}" alt="SARITA LOGO" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-lg-auto mb-2 mb-lg-0 gap-lg-3">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Tentang</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Kontak</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false"> Profil </a>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li><a class="dropdown-item"
                                        href="{{ url_for('views.profil', username=current_user.username ) }}">Lihat
                                        Profil</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('auth.logout' ) }}">Keluar</a></li>
                            </ul>
                        </li>
                        <!-- <li class="nav-item ms-lg-3 mt-3 mt-lg-0">
                            <a >Masuk</a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7 col-12">
                    <div class="d-flex mt-lg-3 flex-column">
                        <form action="" method="post">
                            <textarea name="tulisan" id="tulisan" style="resize: none" class="form-control mb-2"
                                id="exampleFormControlTextarea1" rows="5" placeholder="Tulis apapun disini..."
                                required></textarea>
                            <div class="form-check mb-3">
                                <input type="checkbox" class="form-check-input" id="anonim" name="anonim">
                                <label for="anonim" class="form-check-label">Tandai sebagai anonim</label>
                            </div>
                            <button type="submit" class="btn btn-purple w-100 rounded-pill mb-2"><i
                                    class="bi bi-pencil-fill me-2" id="openChat"></i> Posting Tulisan</button>
                        </form>
                        <a href="{{ url_for('views.chat', room=current_user.room_id, page_num=1) }}" role="button"
                            class="btn btn-outline-purple w-100 rounded-pill mb-2"><i class="bi bi-chat-fill me-2"
                                id="openChat"></i> Chat Room</a>
                    </div>
                </div>
                <div class="col-12 col-lg-7 d-flex flex-column align-items-center mt-3">
                    {% for posts in postingan %}
                    {% if posts.status %}
                    <div class="card w-100 mb-3">
                        {% for users in user %}
                        {% if users.id == posts.user_id %}
                        {% if posts.anonym == 'on' %}
                        <div class="card-header">Anonim</div>
                        {% else %}
                        <div class="card-header">{{ users.username }}</div>
                        {% endif %}
                        {% endif %}
                        {% endfor %}
                        <div class="card-body">
                            <p class="text-truncate">{{ posts.konten }}</p>
                            <a class="btn btn-yellow rounded-3" role="button" href="#ceritaModal" data-bs-toggle="modal"
                                data-bs-target="#ceritaModal">Lanjut baca</a>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <nav aria-label="...">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <a class="page-link">Previous</a>
                            </li>
                            <li class="page-item active" aria-current="page"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </main>
    <footer></footer>

    <!-- LOGIN MODAL -->
    <div class="modal fade" id="ceritaModal" tabindex="-1" aria-labelledby="ceritaModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
            <div class="modal-content rounded-4 p-lg-3">
                <!-- <div class="modal-header">
                    <h1 class="modal-title fs-5" id="ceritaModalLabel">Masuk</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div> -->
                <div class="modal-body">
                    <blockquote>

                        {% for posts in postingan %}
                        {% if posts.status %}
                        <p class="text-break">
                        <p class="text-truncate">{{ posts.konten }}</p>
                        </p>
                        {% endif %}
                        {% endfor %}
                    </blockquote>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        /*
        const socket = io({autoConnect: false});

        document.getElementById("openChat").addEventListener("click", function(){
            let username = "{{username}}";
            socket.connect();

            socket.on("connect", function(){
                socket.emit("user_join", username);
            })
        })*/
    </script>
</body>
{% endblock %}

App/templates/chat_room.html
{% extends 'base.html' %} {% block title %} Chat Room {% endblock %} {% block body %}

<body>
    <img src="{{ url_for('static', filename='src/img/SR element.png' ) }}"
        class="position-absolute bottom-0 end-0 d-none d-lg-block" alt="" />
    <img src="{{ url_for('static', filename='src/img/SR element 2.png' ) }}"
        class="position-absolute bottom-0 start-0 d-none d-lg-block" alt="" />
    <header>
        <nav class="navbar navbar-expand-lg bg-white">
            <div class="container">
                <a class="navbar-brand" href="/"><img
                        src="{{ url_for('static', filename='src/img/SARITA LOGO 2.png' ) }}" alt="SARITA LOGO" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-lg-auto mb-2 mb-lg-0 gap-lg-3">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Tentang</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Kontak</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false"> Profil </a>
                            <ul class="dropdown-menu">
                                {% if current_user.account_type == 'admin' %}
                                <li><a class="dropdown-item"
                                        href="{{ url_for('views.adminProfile', username=current_user.username) }}">Lihat
                                        Profil</a>
                                </li>
                                {% else %}
                                <li><a class="dropdown-item"
                                        href="{{ url_for('views.profil', username=current_user.username ) }}">Lihat
                                        Profil</a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{{ url_for('auth.logout' ) }}">Keluar</a></li>
                            </ul>
                        </li>
                        <!-- <li class="nav-item ms-lg-3 mt-3 mt-lg-0">
                            <a class="btn btn-yellow fw-bold rounded-3" role="button" href="#friendList"
                                data-bs-toggle="modal" data-bs-target="#friendList">Masuk</a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            <div class="row pt-lg-5 d-lg-flex justify-content-lg-center">
                <div class="col-12 col-lg-8 mb-3 mb-lg-0">
                    <div class="card mb-3">
                        <div class="card-header fw-bold bg-purple d-flex align-items-center justify-content-between">
                            <div>
                                <p class="mb-0">Chat Room</p>
                                <small class="fw-normal text-white-50 room-name"></small>
                            </div>
                            <!-- <input class="visually-hidden" type="text" name="user_ids" id="user_ids" value="Haidar"> -->
                            <div class="dropdown">
                                <button class="btn btn-purple" type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    <i class="bi bi-three-dots-vertical"></i>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li>
                                        <a class="dropdown-item" href="#clearChat" data-bs-toggle="modal"
                                            data-bs-target="#clearChat"><i class="bi bi-trash-fill me-2"></i> Bersihkan
                                            Chat</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body chat-room" id="chatRoom">
                            <ul class="list-unstyled d-flex justify-content-end mb-0 flex-column h-100"
                                id="chatContainer">
                                {% if msgs.has_next %}
                                <div class="d-flex flex-column align-items-center">
                                    <a class="btn btn-secondary rounded-pill"
                                        href="{{ url_for('views.chat', room=room, page_num=msgs.next_num) }}">Pesan
                                        Sebelumnya</a>
                                </div>
                                {% endif %}

                                {% for chats in msgs.items|reverse %}
                                {% if chats.sender == current_user.username %}
                                <div class="text-end small text-muted">{{chats.sender}}</div>
                                <li class="chat-bubble-me rounded-start-5 rounded-bottom-5 p-3 mb-3 ms-auto">
                                    {{chats.pesan }}</li>
                                {% else %}
                                <div class="small text-muted">{{chats.sender}}</div>
                                <li class="chat-bubble-reply rounded-end-5 rounded-bottom-5 p-3 mb-3 me-auto">
                                    {{chats.pesan }}</li>
                                {% endif %}
                                {% endfor %}

                                {% if msgs.has_prev %}
                                <div class="d-flex flex-column align-items-center">
                                    <a class="btn btn-secondary rounded-pill"
                                        href="{{ url_for('views.chat', room=room, page_num=msgs.prev_num) }}">Pesan
                                        Selanjutnya</a>
                                </div>
                                {% endif %}
                            </ul>
                        </div>


                        <div class="px-3">
                            <form action="" method="post">
                                <div class="input-group mb-3">
                                    <textarea autofocus="true" id="message" name="message" type="text"
                                        class="form-control" placeholder="Ketik apapun..." aria-label="Ketik apapun..."
                                        aria-describedby="sendButton" rows="1" maxlength="100"
                                        style="resize: none"></textarea>
                                    <!-- <textarea name="" id="" cols="30" rows="10"></textarea> -->
                                    <button class="btn btn-yellow" type="button" id="sendButton">Kirim <i
                                            class="bi bi-send-fill"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!-- CHAT CLEAR -->
    <div class="modal fade" id="clearChat" tabindex="-1" aria-labelledby="clearChatLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <!-- <div class="modal-header">
                    <p class="modal-title mb-0 fw-bold">Bersihkan Chat</p>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div> -->
                <div class="modal-body">
                    <p class="text-center mb-0">Apakah anda yakin akan <span class="fw-bold text-danger">membersihkan
                            semua pesan</span>?</p>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button>
                    <a role="button" href="{{ url_for('views.delete_chat', room=room ) }}"
                        class="btn btn-danger">Hapus!</a>
                </div>
            </div>
        </div>
    </div>

    <script>
        const socket = io({ autoConnect: false });

        window.addEventListener("load", function () {
            let username = `{{ current_user.username }}`;
            var chatRoom = document.querySelector("#chatRoom");

            socket.connect();

            socket.on("connect", function () {
                socket.emit("user_join", `{{room}}`);
                chatRoom.scrollTop = chatRoom.scrollHeight;
            });

            socket.on("leave", function (room) {
                console.log("User " + username + " has leave the room")
                socket.emit("leave", `{{room}}`);
            });

            socket.on("chat", function (data) {
                let chatContainer = document.getElementById("chatContainer");
                let li = document.createElement("li");
                let user_name = document.createElement("span")
                let chatRoom = document.querySelector("#chatRoom");

                // Memeriksa apakah pesan ditujukan untuk pengguna saat ini atau bukan
                if (data["username"] != username) {
                    // Menampilkan pesan hanya jika sesuai dengan ruangan yang benar
                    li.appendChild(document.createTextNode(data["message"]));
                    user_name.appendChild(document.createTextNode(data["username"]));
                    li.classList.add("chat-bubble-reply", "rounded-end-pill", "rounded-bottom-pill", "p-3", "mb-3");
                    user_name.classList.add("small", "text-muted");
                    chatContainer.appendChild(user_name);
                    chatContainer.appendChild(li);
                } else {
                    li.appendChild(document.createTextNode(data["message"]));
                    user_name.appendChild(document.createTextNode(data["username"]));
                    li.classList.add("chat-bubble-me", "rounded-start-pill", "rounded-bottom-pill", "p-3", "mb-3", "ms-auto");
                    user_name.classList.add("text-end", "small", "text-muted");
                    chatContainer.appendChild(user_name);
                    chatContainer.appendChild(li);
                }
                chatRoom.scrollTop = chatRoom.scrollHeight;
            });
        });

        document.getElementById("message").addEventListener("keyup", function (event) {
            if (event.key == "Enter") {
                let message = document.getElementById("message").value;
                let room = `{{room}}`
                //console.log(message + room)
                socket.emit("new_message", message, room);
                document.getElementById("message").value = "";
            }
        });

        // Attach a click event listener to the button
        document.getElementById("sendButton").addEventListener("click", function () {
            let message = document.getElementById("message").value;
            let room = `{{room}}`
            console.log(message + room)
            socket.emit("new_message", message, room);
            document.getElementById("message").value = "";
        });
    </script>

    <script>
        function showPass() {
            const showPassBtn = document.getElementById("showPassBtn");
            const icon = document.getElementById("passIcon");
            const userPass = document.getElementById("userPassword");

            if (userPass.type === "password") {
                userPass.type = "text";
                icon.classList.remove("bi-eye-slash-fill");
                icon.classList.add("bi-eye-fill");
            } else {
                userPass.type = "password";
                icon.classList.remove("bi-eye-fill");
                icon.classList.add("bi-eye-slash-fill");
            }
        }
    </script>

</body>
{% endblock %}